#### ggplot ####

# Tidtverse package include ggplot2
library(tidyverse)
library(ggplot2)

# Data + Coordinate Plane + Geomereical Object + Mapping of Data on to Plane + (X? Y?)

# Load the data
source(here::here("data/day3_objects.R"))

# ggplot(data = <DATA FRAME>) + <GEOM_FUNCTION>(mapping = aes(<VARIABLES>))
# connected with the + operator

p1 <-ggplot(data = gapminder07) + 
    geom_point(mapping = aes(x = log(pop), y = log(gdpPercap))) +
    labs(title = "Relationship between GDP per capita and population in 2007", 
         x = "Natural log of GDP per capita", y = "Natural log of population") 
p1 + theme_bw()

# dplyr and ggplot2 are designed to work well together
# EX1: Plot a column chart of total energy generated over time
p2 <- long_gen %>% 
    group_by(datetime) %>% 
    summarise(total_output=sum(output)) %>% 
    ggplot() + 
    geom_col(aes(x=datetime, y=total_output)) + 
    labs(title="Total energy generated, by hour", x="Hour", y="Output (MW)")
 
p2 + theme(plot.background = element_rect(fill = "purple"))

#EX2: Plot a column chart hydroelectric power generated over time
p3 <- long_gen %>% 
    filter(source == "small_hydro" | source == "large_hydro" ) %>%  
    # filter(source %in% c(large_hydro", "small_hydr"))
    # filter(str_detest(source, "hydro"))
    group_by(datetime) %>%                                         
    summarise(total_output=sum(output)) %>% 
    ggplot() + 
    geom_col(aes(x=datetime, y=total_output)) + 
    labs(title="Total hydro power generated, by hour", x="Hour", y="Output (MW)")

# line
imports %>%
ggplot() + 
    geom_line(aes(x=datetime, y=imports), size = 0.8, col = "purple") + 
    labs(title="Energy imports over time", x="Hour", y="Amount imported (MW)")

# area
generation %>% 
    ggplot() + 
    geom_area(aes(x=datetime, y=wind), fill="pink") + 
    labs(title="Hourly wind power generation, Sept 3-9", x="Hour", y="Output (MW)")


# boxplt
long_gen %>% 
    ggplot() + 
    geom_boxplot(aes(x=source, y=output)) + 
    labs(title="Amount of energy generated by each source, Sept 3-9", 
         x="Source type", y="Output (MW)")

# Plot a line of large hydro generation over time, 
# and a smoothed line of the same relationship on top of it.
P4 <-long_gen %>% 
    filter(source == "large_hydro" ) %>%  
    ggplot() + 
    geom_line(aes(x=datetime, y=output), size = 0.8, col = "turquoise3") +
    geom_smooth(aes(x=datetime, y=output),size = 1.0, col = "purple")+
    labs(title="Hydroelectric (large) generation per hour, Sept 3-9", x="Hour", y="Output (MW)")
P4

# EX3
# Create a column chart that shows the total output per source.
P5 <-long_merged_energy %>% 
    group_by(source) %>%                                         
    summarise(total_output=sum(output)) %>% 
    ggplot() + 
    geom_col(aes(x = source, y = total_output), fill = "pink") +
    geom_hline(aes(yintercept = mean(total_output))) +
    labs(title="Total energy generation per hour, Sept 3-9", x="Hour", y="Output (MW)")
P5

# Labels
imports %>%
    ggplot() + 
    geom_line(aes(x=datetime, y=imports), col="red") + 
    labs(title="Energy imports over time in California", subtitle="Hourly data from September 3-9, 2018",
         caption="Source: California Energy Commission", x="Hour", y="Amount imported (MW)")

# Scales
imports %>%
    ggplot() + geom_line(aes(x=datetime, y=imports), col="red") + 
    scale_x_datetime(date_labels="%H:%M", date_breaks="12 hours") +
    labs(title="Energy imports over time in California", subtitle="Hourly data from September 3-9, 2018", 
         x="Hour", y="Amount imported (MW)") +  theme(axis.text.x=element_text(angle=45, hjust=1, size=12))

# Cord
long_gen %>% 
    mutate(date=lubridate::date(datetime)) %>% 
    group_by(date) %>% summarise(output=sum(output)) %>% 
    ggplot() + geom_col(aes(x=date, y=output)) + 
    labs(title="Total energy generated, by day", x="Day", y="Output (MW)") + 
    coord_flip()

# Group
long_merged_energy %>%
    ggplot() + 
    geom_line(aes(x=datetime, y=output, group=source, col=source)) + # group=source can be omitted in this case
    labs(title="Output by energy source over time", subtitle="Hourly data from September 3-9, 2018", 
         x="Hour", y="Output (MW)")

# EX4
p6 <-long_merged_energy %>%
    filter(source %in% c("wind", "solar", "geothermal")) %>% 
    ggplot() + 
    geom_line(aes(x=datetime, y=output, group=source, col=source), size =1.5) +
    # scale_color_brewer(palette="Accent", name="Energy source") + 
    # scale_color_brewer(palette = "Set1")
    labs(title="Output by energy source over time", subtitle="Hourly data from September 3-9, 2018", 
         x="Hour", y="Output (MW)")
p6

# Energy use by day
long_merged_energy %>% 
    mutate(date=lubridate::date(datetime)) %>% 
    group_by(date, source) %>% 
    summarize(output=sum(output)) %>% 
    ggplot() + 
    geom_col(aes(x=date, y=output, group=source, fill=source)) + 
    labs(title="Energy use by day", x="Day", y="Output (MW)")

# dodge
long_merged_energy %>% 
    mutate(date=lubridate::date(datetime)) %>% 
    group_by(date, source) %>% 
    summarize(output=sum(output)) %>% 
    ggplot() + 
    geom_col(aes(x=date, y=output, group=source, fill=source), position="dodge") + 
    labs(title="Energy use by day", x="Day", y="Output (MW)")

# group by day
# Prepare data
long_merged_energy_regroup <- long_merged_energy %>%
    rename(type = source) %>% 
    merge(regroup, by = "type") %>% 
    mutate(date=lubridate::date(datetime)) %>% 
    group_by(date, group) %>%
    summarise(output=sum(output))

# Take a look at our prepared data
head(long_merged_energy_regroup)

# 1
long_merged_energy_regroup %>% 
    ggplot() + 
    geom_line(aes(x=date, y=output, group=group, col=group), size=0.8) +
    geom_point(aes(x=date, y=output, group=group, shape=group)) + 
    labs(title="Output by source group over time", subtitle="Data collected during September 3-9, 2018", 
         x="Date", y="Output (MW)")

# 2
long_merged_energy_regroup %>% 
    ggplot() + 
    geom_line(aes(x=date, y=output, group=group, linetype=group), size=1) +
    labs(title="Output by source group over time", subtitle="Data collected during September 3-9, 2018", 
         x="Date", y="Output (MW)")

# Sizes and alpha
gapminder07 %>% 
    ggplot() + 
    geom_point(aes(x=log(gdpPercap), y=lifeExp, size=pop, col=continent)) + 
    scale_size_continuous(name="Population") + scale_color_discrete(name="Continent") +
    labs(title="Life expectancy as a function of GDP per capita in 2007", 
         x="Logged GDP per capita", y="Life expectancy")

# EX5
# Visualize the average output for each hour of the day, grouped by source
ex5 <- long_merged_energy %>% 
    mutate(hour=lubridate::hour(datetime)) %>% 
    group_by(hour, source) %>% 
    summarize(output=sum(output)) %>%
    ggplot() + 
    geom_area(aes(x=hour, y=output, fill=factor(source))) + 
    scale_fill_brewer(palette="Set3", name="Source") + 
    labs(title="Average hourly output by source", 
         subtitle="Data collected during September 3-9",
         x="Hour of the day", y="Output (MW)") + 
    theme_bw()

# Comparing generation patterns
long_gen %>% 
    ggplot() + 
    geom_line(aes(x = datetime, y = output)) + 
    facet_wrap(~source) + 
    labs(title="Generation over time, by energy source", subtitle="Hourly data from September 3-9, 2018", 
         x="Hour", y="Output (MW)")

long_gen %>% 
    ggplot() + 
    geom_line(aes(x = datetime, y = output)) + 
    facet_wrap(~source, scales="free") + 
    labs(title="Generation over time, by energy source", subtitle="Hourly data from September 3-9, 2018", 
         x="Hour", y="Output (MW)")

# Facets
long_gen_regroup <- long_gen %>%
    rename(type = source) %>% 
    merge(regroup, by="type")

head(long_gen_regroup)

long_gen_regroup %>% ggplot() + 
    geom_line(aes(x=datetime, y=output, group=group, col=group), size=1) + 
    scale_color_brewer(palette="Set1", name="Type of energy source") +
    facet_wrap(~type, scales="free") + 
    labs(title="Generation over time, by energy source", subtitle="Hourly data from September 3-9, 2018", x="Hour", y="Output (MW)") + 
    theme(legend.position = "bottom")
