---
title: "day2_exercise"
author: "Xiaoling Zhang"
date: "9/18/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(lubridate)
generation <- read.csv(here::here("data/ca_energy_generation.csv"), 
                       stringsAsFactors = F)
imports <- read.csv(here::here("data/ca_energy_imports.csv"), 
                    stringsAsFactors = F)

generation <- mutate(generation, datetime = as_datetime(datetime))
imports <- mutate(imports, datetime = as_datetime(datetime))
```

```{r}
library(reshape2)
long_ca_energy <- generation %>%
  inner_join(imports, by = "datetime") %>% 
  melt(id.vars = "datetime",
       variable.name = "source",
       value.name = "output")
long_ca_energy
```
```{r}
long_ca_energy <- long_ca_energy %>%
  mutate(day = as_date(datetime),
         log_output = log(output)) %>%
  group_by(day) %>%
  mutate(total_daily_output = sum(output, na.rm = T)) %>% 
  ungroup() %>% 
  mutate(per_output = output/total_daily_output)
```
```{r}
long_ca_energy
```


```{r}
long_ca_energy %>% 
  group_by(source) %>% 
  summarize(mean_hourly = mean(output, na.rm = T)) %>% 
  arrange(desc(mean_hourly))
```


```{r}
long_ca_energy %>% 
  group_by(source) %>% 
  summarize(mean_hourly = mean(output, na.rm = T)) %>% 
  arrange(mean_hourly)
```



```{r}
long_ca_energy %>% 
  group_by(day, source) %>% 
  summarize(mean_daily = mean(output, na.rm = T)) %>% 
  arrange(desc(mean_daily))

long_ca_energy %>% 
  group_by(day, source) %>% 
  summarize(mean_daily = mean(output, na.rm = T)) %>% 
  arrange(mean_daily)
```



```{r}
long_ca_energy %>% 
  group_by(source) %>% 
  summarize(variance = var(output, na.rm = T)) %>% 
  arrange(desc(variance))

long_ca_energy %>% 
  group_by(source) %>% 
  summarize(variance = var(output, na.rm = T)) %>% 
  arrange(variance)
```


```{r}
regroup <- read.csv(here::here("data/ca_energy_regroup.csv"), 
                    stringsAsFactors = F)
regroup_energy <- merge(long_ca_energy, regroup, by.x = 'source', by.y = 'type')
```


```{r}
regroup_energy %>% group_by(group) %>% summarize(mean_hourly = mean(output, na.rm = T)) %>% 
  arrange(desc(mean_hourly))
```


